USE TroptechModasDB;

-- 1)

SELECT E.Estado, SUM(CASE WHEN E.Estado IS NOT NULL THEN V.Valor ELSE 0 END)
FROM VENDA V INNER JOIN CLIENTES C ON (V.CadastroUnicoCliente = C.CadastroUnico) INNER JOIN ENDERECO E ON (C.EnderecoId = E.Id)
GROUP BY E.Estado;

-- 2)
-- a)

CREATE TABLE PAIS
(
    Id INT IDENTITY(1,1) NOT NULL,
    Nome VARCHAR(255) NOT NULL,

    CONSTRAINT PK_IdPais PRIMARY KEY (Id),
);

GO

-- b)

CREATE TABLE ESTADO
(
    Id INT IDENTITY(1,1) NOT NULL,
    Nome VARCHAR(255) NOT NULL,
    PaisId INT NOT NULL,

    CONSTRAINT PK_IdEstado PRIMARY KEY (Id),
    CONSTRAINT FK_IdPaisEstado FOREIGN KEY (PaisId) REFERENCES PAIS,
);

GO

-- c)

INSERT INTO Pais
SELECT Pais
FROM ENDERECO
GROUP BY Pais;

-- d)

SELECT *
FROM ESTADO;

INSERT INTO ESTADO
SELECT E.Estado, P.Id
FROM ENDERECO E INNER JOIN PAIS P ON (E.Pais LIKE P.Nome)
GROUP BY E.Estado, P.Id;

-- e)

ALTER TABLE ENDERECO ADD EstadoID INT NULL;
GO
ALTER TABLE ENDERECO ADD CONSTRAINT FK_IdEstadoEndereco FOREIGN KEY (EnderecoId) REFERENCES ESTADO;

GO

-- f)

UPDATE ENDERECO SET EstadoID = E.Id FROM ENDERECO EN INNER JOIN ESTADO E ON (EN.Estado LIKE E.Nome);

-- g)

ALTER TABLE ENDERECO DROP COLUMN Estado, Pais;

GO

-- h) 

ALTER TABLE ENDERECO ALTER COLUMN 
                EstadoID INT NOT NULL;

GO